{% set name = "TextGrid" %}
{% set version = "1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 78c459da90a2d2b8c5b66bcf78160bc5517518df6070712b8d9222bf2af87c9c

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - textgrid

about:
  home: https://github.com/kylebgorman/textgrid
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python module for interacting with Praat TextGrid files."
  dev_url: https://github.com/kylebgorman/textgrid

extra:
  recipe-maintainers:
    - wietsedv
